# Generated by Django 2.2.6 on 2019-10-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(choices=[('opc', 'OPC'), ('ialarm', 'iAlarm'), ('replicator', 'Replicator')], default=None, max_length=10)),
                ('name_opc', models.CharField(max_length=50)),
                ('mqtt_opc', models.BooleanField(default=False)),
                ('mCon_opc', models.CharField(max_length=10)),
                ('sCon_opc', models.CharField(max_length=10)),
                ('sql_opc', models.BooleanField(default=False)),
                ('host_opc', models.CharField(max_length=50)),
                ('path_opc', models.CharField(max_length=100)),
                ('logfile_opc', models.CharField(max_length=50)),
                ('interval_opc', models.DecimalField(decimal_places=3, max_digits=4)),
                ('spsVar_opc', models.CharField(max_length=50)),
                ('checkconfig_opc', models.BooleanField(default=True)),
                ('reconnect_opc', models.BooleanField(default=False)),
                ('name_ialarm', models.CharField(max_length=50)),
                ('mqtt_ialarm', models.BooleanField(default=False)),
                ('mCon_ialarm', models.CharField(max_length=10)),
                ('sCon_ialarm', models.CharField(max_length=10)),
                ('database_ialarm', models.CharField(max_length=50)),
                ('tables_ialarm', models.CharField(max_length=100)),
                ('logfile_ialarm', models.CharField(max_length=50)),
                ('interval_ialarm', models.DecimalField(decimal_places=3, max_digits=4)),
                ('reconnect_ialarm', models.BooleanField(default=True)),
                ('format_ialarm', models.CharField(max_length=50)),
                ('machine_name_ialarm', models.CharField(max_length=50)),
                ('dataLimit_ialarm', models.DecimalField(decimal_places=0, max_digits=5)),
                ('name_replicator', models.CharField(max_length=50)),
                ('mqtt_replicator', models.BooleanField(default=False)),
                ('mCon_replicator', models.CharField(max_length=10)),
                ('sCon_replicator', models.CharField(max_length=10)),
                ('sql_replicator', models.BooleanField(default=False)),
                ('database_replicator', models.CharField(max_length=50)),
                ('tables_replicator', models.CharField(max_length=50)),
                ('logfile_replicator', models.CharField(max_length=50)),
                ('interval_replicator', models.DecimalField(decimal_places=3, max_digits=4)),
                ('reconnect_replicator', models.BooleanField(default=True)),
                ('savefile_replicator', models.CharField(max_length=50)),
                ('replicatorConfig_replicator', models.CharField(max_length=50)),
                ('machine_name_replicator', models.CharField(max_length=50)),
                ('dataLimit_replicator', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MQTTConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('port', models.DecimalField(decimal_places=0, max_digits=4)),
                ('certs', models.BooleanField(default=False)),
                ('cid', models.CharField(max_length=100)),
                ('ca', models.CharField(max_length=100)),
                ('cert', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('tcp', models.CharField(default='tcp', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('format_mqtt', models.CharField(default='{"data":[{"key":"<varname>","timestamp":<timestamp>,"value":"<value>"}]}', max_length=100)),
                ('storeOffline', models.BooleanField(default=True)),
                ('offlineLimit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('signedURL', models.BooleanField(default=False)),
                ('generalTopic', models.CharField(max_length=100)),
                ('alarmTopic', models.CharField(max_length=100)),
                ('dataTopic', models.CharField(default='data', max_length=100)),
                ('alivePing', models.BooleanField(default=True)),
                ('alivePingInterval', models.DecimalField(decimal_places=3, max_digits=4)),
                ('alivePingTopic', models.CharField(default='ping', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SQLConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('useTables', models.BooleanField(default=True)),
                ('tableName', models.CharField(max_length=50)),
                ('poolsize', models.DecimalField(decimal_places=0, max_digits=2)),
                ('connection_type', models.CharField(max_length=50)),
            ],
        ),
    ]
