# Generated by Django 2.2.6 on 2019-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfig',
            name='interval_opc',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
        ),
    ]
