# Generated by Django 2.2.6 on 2019-10-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_auto_20191022_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfig',
            name='dataLimit_ialarm',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='dataLimit_replicator',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=5),
        ),
    ]
