# Generated by Django 2.2.6 on 2019-10-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_auto_20191022_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfig',
            name='interval_replicator',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4),
        ),
    ]
