# Generated by Django 2.2.6 on 2019-10-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.TextField(default='Yodas Soda is not your name, type it in')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
