# Generated by Django 2.2.6 on 2019-10-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_userinfo_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
