# Generated by Django 2.2.6 on 2019-10-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_auto_20191018_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='comments',
            field=models.TextField(),
        ),
    ]
