# Generated by Django 2.2.6 on 2019-10-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_auto_20191018_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
